import { useEffect, useRef, useState } from 'react'
import { BookOpen, ArrowLeft, Clock3, Plus, Settings, Search, Mic, Pause, Play, Square, PanelTop, Download, Check, ChevronRight, X, AudioLines } from 'lucide-react'
import './App.css'
import { SubtitleOverlay } from './SubtitleOverlay'

type Course = {id:string;name:string;accentCode:string;createdAt:string;scheduleType:string;scheduleDate:string;scheduleWeekday?:number;scheduleMonthDay?:number;scheduleTime?:string}
type RecordSummary = {id:string;course_id?:string;title:string;date:string;duration:number;preview:string}
type Caption = {id:string;text:string;final:boolean;start?:number;utterance?:number}
type LanguageRow = {english:string;chinese:string;original:string;members:string[];status:string;error?:string}
type Session = {speaker_names?:Record<string,string>;content_edits?:Record<string,{speaker:string;original:string;translated:string}>;speaker_rows?:Record<string,{label:string;speaker_id:number;role:string}>;phase:string;error?:string;rows:Caption[];live:{stable:string;unstable:string}[];language_rows:Record<string,LanguageRow>;metrics:{captured_seconds:number;rms:number;stage?:string};config:{course_id?:string;course_name?:string}}
type Preferences={noise_reduction:boolean;model:string;device:number|null;font_size:number;auto_scroll:boolean}
type Config={session_token:string;models:{name:string;ready:boolean}[];devices:{id:number;name:string;default:boolean}[];settings:Preferences;translation_configured:boolean}
type Library={courses:Course[];records:RecordSummary[]}
type Page='courses'|'course'|'history'|'settings'|'recording'|'record'
const duration=(seconds=0)=>`${Math.floor(seconds/3600)}:${Math.floor(seconds/60%60).toString().padStart(2,'0')}:${Math.floor(seconds%60).toString().padStart(2,'0')}`
const dateLabel=(value:string)=>{const date=new Date(value);return Number.isNaN(date.getTime())?'未设置日期':date.toLocaleString('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'})}
const accentLabel=(value?:string)=>value==='en-US'?'英语（美国）':value==='en-GB'?'英语（英国）':'英语 · 自动'
const repeatLabels:Record<string,string>={single:'单次',daily:'每日',weekly:'每周',monthly:'每月'}
const weekdays=['星期日','星期一','星期二','星期三','星期四','星期五','星期六']
const scheduleLabel=(course:Course)=>course.scheduleType==='weekly'&&course.scheduleWeekday!==undefined?`每周${weekdays[course.scheduleWeekday]} · ${course.scheduleTime||'未设置时间'}`:course.scheduleType==='monthly'&&course.scheduleMonthDay?`每月${course.scheduleMonthDay}号 · ${course.scheduleTime||'未设置时间'}`:course.scheduleType==='daily'&&course.scheduleTime?`每日 · ${course.scheduleTime}`:(repeatLabels[course.scheduleType]||'单次')+' · '+(course.scheduleDate?dateLabel(course.scheduleDate):dateLabel(course.createdAt))
const phaseLabel:Record<string,string>={idle:'准备就绪',loading:'正在加载语音模型…',recording:'正在录音',paused:'录音已暂停',stopping:'正在保存与收尾…',done:'录音已保存',error:'录音异常'}

function pairedRows(session:Session|null){
 if(!session)return []
 const language=session.language_rows||{}, hidden=new Set(Object.values(language).flatMap(r=>r.members?.slice(1)||[]))
 return session.rows.filter(r=>!hidden.has(r.id)).map(row=>({id:row.id,speaker:session.speaker_rows?.[String(row.utterance)]?.label||'',original:language[row.id]?.english||row.text,translated:language[row.id]?.chinese||'',...session.content_edits?.[row.id],...(session.speaker_rows?.[String(row.utterance)]?.speaker_id!=null&&session.speaker_names?.[String(session.speaker_rows[String(row.utterance)].speaker_id)]?{speaker:session.speaker_names[String(session.speaker_rows[String(row.utterance)].speaker_id)]}:{}),pending:language[row.id]?.status==='error'?'翻译暂不可用':language[row.id]?.status==='queued'?'等待翻译':language[row.id]?.status==='grammar'?'自动校对中':language[row.id]?.status==='translating'?'翻译中…':undefined}))
}
function App(){
 const[contentDraft,setContentDraft]=useState<{rows:{id:string;original:string;translated:string}[];speaker_names:Record<string,string>}|null>(null)
 const[renameRecordId,setRenameRecordId]=useState<string|null>(null)
 const[newWeekday,setNewWeekday]=useState(1),[newMonthDay,setNewMonthDay]=useState(1),[newTime,setNewTime]=useState('09:00')
 const[editingCourse,setEditingCourse]=useState(false),[deleteCourseOpen,setDeleteCourseOpen]=useState(false)
 const[page,setPage]=useState<Page>('courses'),[course,setCourse]=useState<Course|null>(null),[library,setLibrary]=useState<Library>({courses:[],records:[]}),[config,setConfig]=useState<Config|null>(null),[prefs,setPrefs]=useState<Preferences>({noise_reduction:true,model:'small',device:null,font_size:15,auto_scroll:true}),[session,setSession]=useState<Session|null>(null),[record,setRecord]=useState<Session|null>(null),[recordTitle,setRecordTitle]=useState(''),[showNew,setShowNew]=useState(false),[newName,setNewName]=useState(''),[newAccent,setNewAccent]=useState('auto'),[newDate,setNewDate]=useState(''),[newRepeat,setNewRepeat]=useState('single'),[downloads,setDownloads]=useState<Record<string,{status:string;progress:number;error?:string}>>({}),[search,setSearch]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[apiKey,setApiKey]=useState(''),[apiMessage,setApiMessage]=useState(''),[returnPage,setReturnPage]=useState<Page>('history'),[exportMenu,setExportMenu]=useState(false),[renameOpen,setRenameOpen]=useState(false),[renameTitle,setRenameTitle]=useState('')
 const feed=useRef<HTMLDivElement>(null),loaded=useRef(false),followLatest=useRef(true)
 const active=['loading','recording','paused','stopping'].includes(session?.phase||'')
 const refreshLibrary=async()=>{const r=await fetch('/api/library');if(!r.ok)throw Error('课程资料读取失败');setLibrary(await r.json())}
 useEffect(()=>{let disposed=false,timer:ReturnType<typeof setTimeout>;let previous=''
  const initialize=async()=>{try{const r=await fetch('/api/config');if(!r.ok)throw Error('无法连接语音服务');const value:Config=await r.json();if(disposed)return;setConfig(value);setPrefs({...value.settings,noise_reduction:value.settings.noise_reduction??true});await refreshLibrary();loaded.current=true}catch(e){if(!disposed)setNotice((e as Error).message)}}
  const poll=async()=>{try{const r=await fetch('/api/state');if(!r.ok)throw Error('语音服务连接中断');const value:Session=await r.json();if(disposed)return;setSession(value);if(!previous&&['loading','recording','paused','stopping'].includes(value.phase))setPage('recording');const dm=await fetch('/api/model-downloads').then(r=>r.json());if(!disposed){setDownloads(dm.downloads);setConfig(c=>c?{...c,models:dm.models}:c)}if(previous&&previous!==value.phase&&value.phase==='done')void refreshLibrary();previous=value.phase}catch(e){if(!disposed)setNotice((e as Error).message)}finally{if(!disposed)timer=setTimeout(poll,300)}}
  void initialize();void poll();return()=>{disposed=true;clearTimeout(timer)}
 },[])
 useEffect(()=>{if(active&&session?.config.course_id){const selected=library.courses.find(c=>c.id===session.config.course_id);if(selected)setCourse(selected)}},[active,session?.config.course_id,library.courses])
 useEffect(()=>{if(prefs.auto_scroll&&followLatest.current&&feed.current)feed.current.scrollTop=feed.current.scrollHeight},[session,prefs.auto_scroll])
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(t)},[notice])
 async function post(path:string,body:unknown={}){if(!config?.session_token)throw Error('语音服务尚未就绪');const r=await fetch(path,{method:'POST',headers:{'X-Lingo-Token':config.session_token,'Content-Type':'application/json'},body:JSON.stringify(body)});const value=await r.json();if(!r.ok)throw Error(value.error||'操作失败');return value}
 async function action(fn:()=>Promise<void>){setBusy(true);try{await fn()}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
 function navigate(next:Page,selected?:Course){setExportMenu(false);followLatest.current=true;if(active&&next!=='recording'){setNotice('正在录音，请先结束并保存当前课堂。');return}if(selected)setCourse(selected);setPage(next);setSearch('')}
 async function createCourse(){const value=await post(editingCourse?'/api/edit-course':'/api/courses',{id:editingCourse?course?.id:undefined,name:newName,accentCode:newAccent,scheduleDate:newRepeat==='single'?newDate:'',scheduleType:newRepeat,scheduleWeekday:newWeekday,scheduleMonthDay:newMonthDay,scheduleTime:newTime});await refreshLibrary();setCourse(value);setPage('course');setShowNew(false);setEditingCourse(false);setNewName('')}
 async function start(){followLatest.current=true;await post('/api/start',{...prefs,course_id:course?.id,course_name:course?.name,threads:4,partial_interval:1.5,silence:.7});setPage('recording')}
 async function end(){await post('/api/stop');setNotice('正在收尾并保存录音。')}
 async function openRecord(item:RecordSummary){if(active)throw Error('请先结束并保存当前课堂');setExportMenu(false);const r=await fetch('/api/records/'+item.id);const value=await r.json();if(!r.ok)throw Error(value.error);setReturnPage(page==='course'?'course':'history');setRecord(value);setRecordTitle(item.title);setCourse(library.courses.find(c=>c.id===item.course_id)||null);setPage('record');followLatest.current=false}
 async function preference(key:keyof Preferences,value:unknown){const updated={...prefs,[key]:value};setPrefs(updated);await post('/api/preferences',updated)}
 async function closeOverlay(){await post('/api/close-overlay');window.close()}
 async function showOverlay(){const r=await post('/api/subtitle-window');if(!r.native)window.open('/overlay','lingoclass-subtitles','width=820,height=240')}
 async function saveText(text:string,filename:string,format:'txt'|'docx'='txt'){const result=await post('/api/export-text',{text,filename,format});if(result.native){if(result.saved)setNotice('已导出');return}if(format==='docx'){const response=await fetch('/api/export-word',{method:'POST',headers:{'X-Lingo-Token':config!.session_token,'Content-Type':'application/json'},body:JSON.stringify({text,filename})});if(!response.ok)throw Error('Word 导出失败');const url=URL.createObjectURL(await response.blob());const link=document.createElement('a');link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return}const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function textOf(data:Session|null){return pairedRows(data).map(r=>(r.speaker?r.speaker+': ':'')+r.original+(r.translated?'\n'+r.translated:'')).join('\n\n')}
 async function exportTranscript(format:'txt'|'docx'='txt'){setExportMenu(false);if(page==='course'){const items=library.records.filter(r=>r.course_id===course?.id);if(!items.length)throw Error('课程还没有录音');const texts=[];for(const item of items){const response=await fetch('/api/records/'+item.id);const data=await response.json();if(!response.ok)throw Error(data.error||'课堂记录读取失败');texts.push(item.title+'\n'+textOf(data))}await saveText(texts.join('\n\n══════════\n\n'),(course?.name||'课程')+'.'+format,format)}else{let data=page==='record'?record:session;const id=renameRecordId||(record as Session&{id?:string})?.id;if(page==='record'&&id){const response=await fetch('/api/records/'+id);const latest=await response.json();if(!response.ok)throw Error(latest.error||'课堂记录读取失败');data=latest;setRecord(latest)}if(!data)throw Error('没有可导出的内容');await saveText(textOf(data),(page==='record'?recordTitle:course?.name||'课堂录音')+'.'+format,format)}}
 async function renameRecord(){const id=renameRecordId||(record as Session&{id?:string})?.id;if(!id)throw Error('课堂记录编号不可用');await post('/api/rename-record',{id,title:renameTitle});if(id===(record as Session&{id?:string})?.id)setRecordTitle(renameTitle.trim());setRenameRecordId(null);setRenameOpen(false);await refreshLibrary()}
 function exportControl(){return <div className="export-control"><button aria-expanded={exportMenu} disabled={busy} onClick={()=>setExportMenu(!exportMenu)}><Download size={15}/>导出</button>{exportMenu&&<div className="export-menu" role="menu"><button role="menuitem" onClick={()=>void action(()=>exportTranscript('docx'))}>Word 文档 <small>.docx</small></button><button role="menuitem" onClick={()=>void action(()=>exportTranscript('txt'))}>纯文本 <small>.txt</small></button></div>}</div>}


 const current=page==='record'?record:session, captions=pairedRows(current),records=library.records.filter(r=>(page!=='course'||r.course_id===course?.id)&&(!search||(r.title+' '+r.preview).toLowerCase().includes(search.toLowerCase())))
 if(window.location.pathname==='/overlay'){
  document.documentElement.classList.add('overlay-root')
  const latest=pairedRows(session).at(-1),live=session?.live?.at(-1)
  const liveText=live?(live.stable+' '+live.unstable).trim():''
  const current=liveText?{id:(latest?.id||'start')+':live',original:liveText,translated:''}:latest||null
  return <SubtitleOverlay caption={current} onClose={()=>void action(closeOverlay)}/>
 }
 return <div className="app-window">
  <aside className={'sidebar'+(active?' recording-locked':'')}><div className="sidebar-heading"><img src="/app-icon.png" alt=""/><strong>LingoClass</strong><button title="新建课程" className="icon-button" disabled={active} onClick={()=>{setEditingCourse(false);setNewName('');setNewDate('');setNewRepeat('single');setShowNew(true)}}><Plus size={18}/></button></div>
   <nav aria-label="主导航"><button className={page==='courses'?'selected':''} onClick={()=>navigate('courses')}><BookOpen size={17}/>课程</button><button className={page==='history'?'selected':''} onClick={()=>navigate('history')}><Clock3 size={17}/>所有录音</button><button className={page==='settings'?'selected':''} onClick={()=>navigate('settings')}><Settings size={17}/>设置</button></nav>
   <div className="sidebar-label">我的课程</div><div className="course-navigation">{library.courses.map(item=><button key={item.id} className={course?.id===item.id&&['course','recording'].includes(page)?'selected':''} onClick={()=>navigate('course',item)}><BookOpen size={16}/><span><strong>{item.name}</strong><small>{scheduleLabel(item)}</small><small>{library.records.filter(r=>r.course_id===item.id).length} 次录音</small></span></button>)}{!library.courses.length&&<p className="sidebar-empty">在课程页创建第一门课程</p>}</div>
  </aside>
  <main className="detail-pane">
   <header className="toolbar"><div className="toolbar-title">{(page==='record'||page==='recording')&&<button className="icon-button" aria-label="返回课堂列表" disabled={active} onClick={()=>navigate(page==='record'?returnPage:course?'course':'courses')}><ArrowLeft size={18}/></button>}{page==='courses'?'课程':page==='history'?'所有录音':page==='settings'?'设置':page==='record'?recordTitle:course?.name}</div><div className="toolbar-actions">{(page==='history'||page==='course')&&<label className="search-field"><Search size={14}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索录音"/></label>}{page==='courses'&&<button className="primary" disabled={active} onClick={()=>{setEditingCourse(false);setNewName('');setNewDate('');setNewRepeat('single');setShowNew(true)}}><Plus size={15}/>新建课程</button>}{(page==='course'||page==='record'||page==='recording'&&captions.length>0)&&exportControl()}{page==='record'&&<button onClick={()=>{const names:Record<string,string>={};Object.values(record?.speaker_rows||{}).forEach(person=>{if(person.speaker_id!=null)names[String(person.speaker_id)]=record?.speaker_names?.[String(person.speaker_id)]||person.label});setContentDraft({rows:pairedRows(record).map(row=>({id:row.id,original:row.original,translated:row.translated})),speaker_names:names})}}>编辑课堂内容</button>}{page==='record'&&<button onClick={()=>{setRenameRecordId(null);setRenameTitle(recordTitle);setRenameOpen(true)}}>改名</button>}{page==='course'&&<><button disabled={active||busy} onClick={()=>{setEditingCourse(true);setNewName(course?.name||'');setNewAccent(course?.accentCode||'auto');setNewDate(course?.scheduleDate||'');setNewRepeat(course?.scheduleType||'single');setNewWeekday(course?.scheduleWeekday??(course?.scheduleDate?new Date(course.scheduleDate).getDay():1));setNewMonthDay(course?.scheduleMonthDay??(course?.scheduleDate?new Date(course.scheduleDate).getDate():1));setNewTime(course?.scheduleTime||course?.scheduleDate?.slice(11,16)||'09:00');setShowNew(true)}}>编辑课程</button><button disabled={active||busy} onClick={()=>setDeleteCourseOpen(true)}>删除课程</button></>}{page==='course'&&<button className="primary" disabled={busy||!loaded.current} onClick={()=>void action(start)}><Mic size={15}/>开始课堂</button>}</div></header>
   {page==='courses'&&<div className="courses-home"><div className="page-intro"><h1>我的课程</h1><p>选择课程开始课堂；结束后，原文与译文会一起保存。</p></div>{library.courses.length?<div className="course-grid">{library.courses.map(item=><button className="course-card" key={item.id} onClick={()=>navigate('course',item)}><span className="course-card-icon"><BookOpen size={23}/></span><div><h2>{item.name}</h2><p>{scheduleLabel(item)}</p><small>{library.records.filter(r=>r.course_id===item.id).length} 次课堂记录 · {accentLabel(item.accentCode)}</small></div><ChevronRight size={17}/></button>)}</div>:<div className="overview"><BookOpen size={44} strokeWidth={1.2}/><h1>从第一门课程开始</h1><p>设置课程名称与上课时间，随后即可开始录音。<br/>语法校对和翻译会在后台自动完成。</p><button className="primary" onClick={()=>{setEditingCourse(false);setNewName('');setNewDate('');setNewRepeat('single');setShowNew(true)}}><Plus size={15}/>创建课程</button></div>}</div>}
   {(page==='history'||page==='course')&&<div className="record-list-pane">{page==='course'&&course&&<div className="course-summary"><h1>{course.name}</h1><p>{scheduleLabel(course)}</p><span><AudioLines size={14}/>{accentLabel(course.accentCode)} <span className="summary-divider"/> 中文</span></div>}{records.length?<div className="record-list">{records.map(item=><div className="record-list-row" key={item.id}><button className="record-item" onClick={()=>void action(()=>openRecord(item))}><div className="record-symbol"><Mic size={19}/></div><div><h2>{item.title}</h2><p>{dateLabel(item.date)}<span>·</span>{duration(item.duration)}</p><small>{item.preview}</small></div><ChevronRight size={16}/></button><button className="record-edit-button" disabled={active||busy} onClick={()=>{setRenameRecordId(item.id);setRenameTitle(item.title);setRenameOpen(true)}} aria-label={"修改课堂名称："+item.title}>改名</button></div>)}</div>:<div className="overview"><Mic size={45} strokeWidth={1.1}/><h1>{search?'没有匹配的录音':'还没有录音'}</h1><p>{search?'请换一个搜索词。':'开始录音，创建第一份课堂记录。'}</p>{page==='course'&&!search&&<button className="primary" disabled={busy||!loaded.current} onClick={()=>void action(start)}><Mic size={15}/>开始课堂</button>}</div>}</div>}
   {(page==='recording'||page==='record')&&<div className="recording-pane"><div className="recording-header"><span>{accentLabel(course?.accentCode)} → 中文</span><small>{page==='record'?'已保存课堂记录':'原文 · 自动校对 · 自动翻译'}</small></div><div className="transcript-scroll" ref={feed} onScroll={()=>{const el=feed.current;if(el)followLatest.current=el.scrollHeight-el.scrollTop-el.clientHeight<70}} style={{fontSize:prefs.font_size}}>{(captions.length||page==='recording'&&session?.live?.length)?captions.map(row=><section className="transcript-pair" key={row.id}><p className="original">{row.speaker&&<span className="speaker-label">{row.speaker}</span>}{row.original}</p>{row.translated&&<p className="translated">{row.translated}</p>}{row.pending&&!row.translated&&<small className="translation-warning">{row.pending}</small>}</section>):<div className="ready-to-listen"><Mic size={32} strokeWidth={1.3}/><p>{active?'正在聆听…':'准备聆听'}</p><small>{active?'说话后，字幕会自动显示。':'开始录音后，原文、语法校对与翻译会自动更新。'}</small></div>}{page==='recording'&&session?.live?.map((part,i)=><section className="transcript-pair provisional" key={'live-'+i}><p>{part.stable}<span>{part.unstable}</span><i className="live-cursor"/></p></section>)}</div>
    {page==='recording'?<div className="recording-controls"><span className="recording-status"><i className={session?.phase==='recording'?'recording-dot':''}/>{phaseLabel[session?.phase||'idle']}</span><div className="meter" title="麦克风输入电平"><Mic size={14}/><div><span style={{width:Math.min(100,(session?.metrics.rms||0)*500)+'%'}}/></div></div><time>{duration(session?.metrics.captured_seconds)}</time><div className="controls-spacer"/><button title="浮动字幕" onClick={()=>void action(showOverlay)}><PanelTop size={15}/>字幕</button>{!active?<button className="primary" disabled={busy||!loaded.current} onClick={()=>void action(start)}><Mic size={15}/>{session?.phase==='done'?'开始下一次课堂':'开始'}</button>:<><button disabled={busy||!['recording','paused'].includes(session?.phase||'')} onClick={()=>void action(async()=>{await post(session?.phase==='paused'?'/api/resume':'/api/pause')})}>{session?.phase==='paused'?<Play size={14}/>:<Pause size={14}/>} {session?.phase==='paused'?'继续':'暂停'}</button><button disabled={busy||session?.phase==='stopping'} onClick={()=>void action(end)}><Square size={12}/>结束并保存</button></>}</div>:<div className="record-detail-footer"><span>原文与译文已保存 · 可在右上角改名或导出</span></div>}</div>}
   {page==='settings'&&<div className="settings-pane"><h1>设置</h1><section className="settings-group"><h2>语音识别</h2><label><span>识别模型<small>新录音使用此模型</small></span><select value={prefs.model} onChange={e=>void action(()=>preference('model',e.target.value))}>{config?.models.map(item=><option key={item.name} disabled={!item.ready} value={item.name}>{item.name}{item.ready?'':'（未下载）'}</option>)}</select></label><div className="model-download-list">{config?.models.map(item=><div className="model-download-row" key={item.name}><span>{item.name}<small>{item.ready?'已安装':downloads[item.name]?.status==='downloading'?`下载中 ${downloads[item.name].progress}%`:downloads[item.name]?.error||'未安装'}</small></span>{!item.ready&&<button disabled={downloads[item.name]?.status==='downloading'} onClick={()=>void action(async()=>{await post('/api/download-model',{model:item.name});setNotice('模型下载已开始')})}>{downloads[item.name]?.status==='error'?'重试':'下载'}</button>}</div>)}</div><label><span>背景降噪<small>自动减弱环境杂音；异常时可关闭回退。</small></span><input type="checkbox" checked={prefs.noise_reduction!==false} onChange={e=>void action(()=>preference('noise_reduction',e.target.checked))}/></label><label><span>麦克风</span><select value={prefs.device??''} onChange={e=>void action(()=>preference('device',e.target.value===''?null:Number(e.target.value)))}><option value="">系统默认</option>{config?.devices.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></section>
    <section className="settings-group"><h2>字幕</h2><label><span>文字大小</span><select value={prefs.font_size} onChange={e=>void action(()=>preference('font_size',Number(e.target.value)))}>{[13,15,17,19,21].map(n=><option key={n} value={n}>{n} pt</option>)}</select></label><label><span>自动滚动至最新字幕</span><input type="checkbox" checked={prefs.auto_scroll} onChange={e=>void action(()=>preference('auto_scroll',e.target.checked))}/></label></section>
    <section className="settings-group"><h2>后台处理</h2><div className="setting-row"><span>语法校对<small>自动校对原文，保留原始识别内容。</small></span><span className="setting-status"><Check size={14}/>自动</span></div><div className="setting-row"><span>翻译<small>识别稳定内容后自动翻译；未变化的内容复用结果。</small></span><span className="setting-status"><Check size={14}/>自动</span></div><label><span>翻译服务</span><span>Qwen MT Flash</span></label><label className="credential-row"><span>API Key<small>{config?.translation_configured?'已配置 · 启动时自动使用':'一次配置，后续自动运行'}</small></span><input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} autoComplete="off" placeholder={config?.translation_configured?'已保存在系统凭据中':'输入 API Key'}/></label><div className="credential-actions"><small>{apiMessage||'翻译文本发送至已配置服务，按用量计费。'}</small><button disabled={!apiKey.trim()||busy} onClick={()=>void action(async()=>{const value=await post('/api/translation-settings',{key:apiKey});setApiKey('');setApiMessage(value.persisted?'已保存到系统凭据，后续自动使用。':'当前运行已配置；系统凭据保存不可用。');setConfig(config?{...config,translation_configured:value.configured}:null)})}>保存</button></div></section></div>}
  </main>
  {(notice||session?.error)&&<div className="notice" role="status">{notice||session?.error}<button title="关闭提示" className="icon-button" onClick={()=>setNotice('')}><X size={14}/></button></div>}
  {contentDraft&&<div className="sheet-backdrop"><form className="course-sheet classroom-editor" onSubmit={e=>{e.preventDefault();void action(async()=>{const id=(record as Session&{id?:string})?.id;const updated=await post('/api/edit-classroom',{id,...contentDraft});setRecord(updated);setContentDraft(null)})}}><header><button type="button" onClick={()=>setContentDraft(null)}>取消</button><h2>编辑整堂课</h2><button className="primary" disabled={busy||contentDraft.rows.some(r=>!r.original.trim())}>保存全部</button></header><div className="sheet-form"><h3>说话人姓名</h3><small>修改姓名会同步到本堂课中相同声纹的所有段落。</small>{Object.entries(contentDraft.speaker_names).map(([id,name])=><label key={id}>说话人 {id}<input value={name} required maxLength={150} onChange={e=>setContentDraft({...contentDraft,speaker_names:{...contentDraft.speaker_names,[id]:e.target.value}})}/></label>)}<h3>课堂内容</h3>{contentDraft.rows.map((row,index)=><div className="classroom-edit-row" key={row.id}><label>第 {index+1} 段 · 英文<textarea rows={3} value={row.original} required onChange={e=>setContentDraft({...contentDraft,rows:contentDraft.rows.map(r=>r.id===row.id?{...r,original:e.target.value}:r)})}/></label><label>中文<textarea rows={3} value={row.translated} onChange={e=>setContentDraft({...contentDraft,rows:contentDraft.rows.map(r=>r.id===row.id?{...r,translated:e.target.value}:r)})}/></label></div>)}</div></form></div>}
  {renameOpen&&<div className="sheet-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setRenameOpen(false)}}><form className="course-sheet" onSubmit={e=>{e.preventDefault();void action(renameRecord)}}><header><button type="button" onClick={()=>setRenameOpen(false)}>取消</button><h2>修改课堂名称</h2><button className="primary" disabled={!renameTitle.trim()||busy}>保存</button></header><div className="sheet-form"><label>课堂名称<input autoFocus value={renameTitle} onChange={e=>setRenameTitle(e.target.value)} maxLength={150}/></label></div></form></div>}
  {deleteCourseOpen&&<div className="sheet-backdrop"><div className="course-sheet"><header><h2>删除课程</h2></header><div className="sheet-form"><p>删除“{course?.name}”？已有录音会保留在“所有录音”中。</p><div><button onClick={()=>setDeleteCourseOpen(false)}>取消</button> <button disabled={busy} onClick={()=>void action(async()=>{await post('/api/delete-course',{id:course?.id});await refreshLibrary();setCourse(null);setPage('courses');setDeleteCourseOpen(false)})}>删除课程</button></div></div></div></div>}
  {showNew&&<div className="sheet-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setShowNew(false)}}><form className="course-sheet" onSubmit={e=>{e.preventDefault();void action(createCourse)}}><header><button type="button" onClick={()=>setShowNew(false)}>取消</button><h2>{editingCourse?'编辑课程':'新建课程'}</h2><button className="primary" disabled={!newName.trim()||busy}>{editingCourse?'保存':'创建'}</button></header><div className="sheet-form"><label>课程名称<input autoFocus value={newName} onChange={e=>setNewName(e.target.value)} placeholder="例如：哲学 176"/></label><label>授课语言<select value={newAccent} onChange={e=>setNewAccent(e.target.value)}><option value="auto">英语 · 自动</option><option value="en-US">英语（美国）</option><option value="en-GB">英语（英国）</option></select></label><label>翻译语言<span className="fixed-field">简体中文</span></label><label>重复方式<select value={newRepeat} onChange={e=>setNewRepeat(e.target.value)}>{Object.entries(repeatLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{newRepeat==='single'?<label>上课日期与时间<input type="datetime-local" value={newDate} onChange={e=>setNewDate(e.target.value)}/></label>:<>{newRepeat==='weekly'&&<label>上课星期<select value={newWeekday} onChange={e=>setNewWeekday(Number(e.target.value))}>{[1,2,3,4,5,6,0].map(day=><option key={day} value={day}>{weekdays[day]}</option>)}</select></label>}{newRepeat==='monthly'&&<label>每月日期<select value={newMonthDay} onChange={e=>setNewMonthDay(Number(e.target.value))}>{Array.from({length:31},(_,i)=>i+1).map(day=><option key={day} value={day}>{day}号</option>)}</select></label>}<label>上课时间<input type="time" required value={newTime} onChange={e=>setNewTime(e.target.value)}/></label></>}</div></form></div>}
 </div>
}
export default App


